### ISSUE TITLE
Cannot use SharedMailbox as Grantor filter?

### ISSUE THREAD

**Issue by snurbnacnud** [GruberMarkus/Export-RecipientPermissions#14]
Hi Markus, 

I used your script in the following way, and created a transcript as to see why I don't get any results.

.\Export-RecipientPermissions.ps1 -ExportFromOnPrem $true -ExchangeConnectionUriList "http://xxx/PowerShell" -UseDefaultCredential $true -GrantorFilter "`$Grantor.RecipientTypeDetails -ieq 'SharedMailbox'"

I see this error in the transcript:

TerminatingError(): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot process argument transformation on parameter 'RecipientTypeDetails'. Cannot convert value "!!!Fail!!!" to type "Microsoft.Exchange.Data.Directory.Recipient.RecipientTypeDetails[]". Error: "Cannot convert value "!!!Fail!!!" to type "Microsoft.Exchange.Data.Directory.Recipient.RecipientTypeDetails". Error: "Unable to match the identifier name !!!Fail!!! to a valid enumerator name. Specify one of the following enumerator names and try again:

Can you help me with this?

**Comment by GruberMarkus** [comment]
Hi snurbnacnud,

this error is expected. It only appears in the transcript, but not in the regular script output. This is because how PowerShell handles error output in the transcript.

The error is not only expected, but neccessary: Export-RecipientPermissions uses the invalid RecipientTypeDetail '!!!Fail!!!', so that the valid types - which vary between on-prem and cloud, and according to your permissions - can be extracted from the error message.


Can you confirm that the export only contains grantors with a RecipientTypeDetail of 'SharedMailbox'?

**Comment by GruberMarkus** [comment]
I overlooked that your wrote that your result file does not contain any results.

As Export-RecipientPermissions does not execute Exchange PowerShell command on the client, but on the server side, the data model is a bit different. This means that some attributes are handled different - for example, the value RecipientTypeDetails in $GrantorFilter is not stores in $GrantorFilter.RecipientTypeDetails but in $GrantorFilter.RecipientTypeDetails.Value.

So the correct command is
```
.\Export-RecipientPermissions.ps1 -ExportFromOnPrem $true -ExchangeConnectionUriList "http://xxx/PowerShell" -UseDefaultCredential $true -GrantorFilter "`$Grantor.RecipientTypeDetails.Value -ieq 'SharedMailbox'"
```

Please let me know if this solves your problem.


This behavior is correctly documented in the script's help, but not in its README. I will update this with the next release.

**Comment by snurbnacnud** [comment]
Hi Markus,

Thank you very much for your quick response. Adding the Value attribute to the filter seems to do the trick. The script is still running but the csv is being filled.

Best regards,

Duncan
