### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by bmartins-EUDA** [GruberMarkus/Export-RecipientPermissions#38]
### Issue happens in the latest release

- [X] I confirm that the issue happens in the latest release of Export-RecipientPermissions

### Previously solved issues and documentation

- [X] I have searched through previous issues and documentation, but have not found an answer to my issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I am just trying to run the script for the first time, and no matter if I save it with UTF-8 or ANSI encoding, I always get the error below.

Any ideas?

Thanks and keep up the good work, Markus!

### Verbose log

```Text
"2024-09-23T16:45:16+01:00";"Import moderators";"Cmdlet 'Get-DistributionGroup', Filter ''((name -like ''�*'') -and (ModerationEnabled -eq `$true))''";"  ConnectExchange, try 3/3, failed, giving up
    ScriptBlock: Get-DistributionGroup -Filter '((name -like ''�*'') -and (ModerationEnabled -eq `$true))' -ResultSize 
Unlimited -ErrorAction Stop -WarningAction SilentlyContinue
    ScriptBlock expanded: Get-DistributionGroup -Filter '((name -like ''�*'') -and (ModerationEnabled -eq $true))' 
-ResultSize Unlimited -ErrorAction Stop -WarningAction SilentlyContinue
    Error: Active Directory operation failed on dc.domain.com. This error is not retriable. Active directory 
response: The 
search filter is invalid.
At line:121 char:21
+ ...             $ConnectExchangeTempReturnValue = Invoke-Command -Session ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-DistributionGroup], ADOperationException
    + FullyQualifiedErrorId : [Server=exchserver,RequestId=cecafbf3-4ca4-4840-a581-94b2f0ffb768,TimeStamp=23/09/2024 
15:45:16] [FailureCategory=Cmdlet-ADOperationException] 
B341F698,Microsoft.Exchange.Management.RecipientTasks.GetDistributionGroup
```

**Comment by GruberMarkus** [comment]
Good morning Bruno!

You write that you are saving the script file. Do you download the source code, or do you download one of the release packages from https://github.com/GruberMarkus/Export-RecipientPermissions/releases?

Because with the later, you only need to extract the ZIP file and do not need to save anything separately.

The direct link to the current release package for v3.2.0 is https://github.com/GruberMarkus/Export-RecipientPermissions/releases/download/v3.2.0/Export-RecipientPermissions_v3.2.0.zip.

**Comment by bmartins-EUDA** [comment]
> Good morning Bruno!
> 
> You write that you are saving the script file. Do you download the source code, or do you download one of the release packages from https://github.com/GruberMarkus/Export-RecipientPermissions/releases?
> 
> Because with the later, you only need to extract the ZIP file and do not need to save anything separately.
> 
> The direct link to the current release package for v3.2.0 is https://github.com/GruberMarkus/Export-RecipientPermissions/releases/download/v3.2.0/Export-RecipientPermissions_v3.2.0.zip.

I downloaded it directly from the 'releases' page. I have the same encoding issue on two different machines (a client and the Exchange server itself).

Thank you!

**Comment by GruberMarkus** [comment]
It seems you have a recipient whose name attribute starts with a unicode character causing this problem.

To find out which recipient this is, manually check the output of `Get-Recipient -ResultSize Unlimited | Where-Object { $_.Name -inotmatch '^[a-z0-9\.]' } | Select-Object -Property @{Name="NameFirstCharUnusual";Expression={$_.Name.Substring(0,1)}}, Name, PrimarySmtpAddress`.

Do I assume correctly that you do not get other errors and see moderator for recipients whose Name attribute starts with a-z0-9?

**Comment by bmartins-EUDA** [comment]
Indeed I have a bunch of entries there.
Your tip made me realize I had an object with the '�' character in the Display Name.

I fixed it and the issue is gone!

Now I am getting another error, but I'll troubleshoot it further.
`Error: ea294853-8f76-4721-92e5-15d561509332 isn't a mailbox user.`

Thank you very much, Markus, and have a lovely weekend!

**Comment by GruberMarkus** [comment]
My pleasure!

The Unicode character should work anyhow - it seems you have found a bug in Get-DistributionGroup or maybe even in all Exchange cmdlets that support the "-Filter" property.


Do you have details on the `ea294853-8f76-4721-92e5-15d561509332 isn't a mailbox user.` error?

You can find the recipient to the GUID with `Get-Recipient ea294853-8f76-4721-92e5-15d561509332`. A `Set-Mailbox` without parameters may reveal if the recipient misses attributes and show hints how to add them. `Set-Mailbox -ApplyMandatoryProperties` might also help.

**Comment by bmartins-EUDA** [comment]
It's not an on-premises mailbox but hosted in Microsoft 365 instead (meaning it's a mail-user object on-premises).

**Comment by GruberMarkus** [comment]
Please provide logs when executing Export-RecipientPermissions with the "-verbose" parameter, as well as the error file.

**Comment by bmartins-EUDA** [comment]
> Please provide logs when executing Export-RecipientPermissions with the "-verbose" parameter, as well as the error file.

Here it is!
[Export-RecipientPermissions_20240927T151650+0100_Error.csv](https://github.com/user-attachments/files/17189889/Export-RecipientPermissions_20240927T151650%2B0100_Error.csv)
[script_execution.log](https://github.com/user-attachments/files/17189890/script_execution.log)

**Comment by GruberMarkus** [comment]
That is the same recipient as before, ea294853-8f76-4721-92e5-15d561509332. The script execution itself has no problems.

When you execute `Get-MailboxPermission -identity ea294853-8f76-4721-92e5-15d561509332 -resultsize unlimited 
-ErrorAction Stop -WarningAction silentlycontinue` on-prem, it must result in an error.

This is expected as Get-MailboxPermission usually does not work cross-premises. So, you can ignore this error - but you will also not have the permissions for this mailbox in the report.

To solve this, you either have to Export-RecipientPermissions twice, once for on-prem and once for the cloud, and then combine the result files.

It is also possible to directly add this feature to Export-RecipientPermissions, I estimate an effort of two or three days via the fee-based support option.

**Comment by bmartins-EUDA** [comment]
Many thanks for the clarification! I can live with it as it is.
Have a nice week, Markus!
